apiVersion: v1                                                           
kind: Pod                                                                
metadata:                                                                
  name: glusterfs                                                        
spec:                                                                    
  containers:                                                            
  - name: glusterfs                                                      
    image: nginx                                                         
    volumeMounts:                                                        
    - mountPath: "/mnt/glusterfs"                                        
      name: glusterfsvol                                                 
  volumes:                                                               
  - name: glusterfsvol                                                   
    glusterfs:                                                           
      endpoints: glusterfs-cluster                                       
      path: gv0                                                          
      readOnly: false
